### ISSUE TITLE
vibrating content in a scroll area

### ISSUE THREAD

**Issue by JosephABudd** [david-vanderson/dvui#155]
A scroll area keeps re-framing its content, first one way and then another way, over and over again non-stop. The visual effect is that of a vibration.

The complete source code with a full description of the issue can be found at [source code](https://github.com/JosephABudd/issue)

A screen shot is shown below. The content at the right of the vertical tab-bar is what vibrates.

![Screenshot from 2024-10-13 20-35-31](https://github.com/user-attachments/assets/53e78c52-c5fb-4565-a622-a3a1e182775a)

**Comment by david-vanderson** [comment]
Sorry about that, and thank you so much for the thorough write up!  I was able to reproduce that vibration effect if the size of the window was just right so that adding the vertical scroll bar on the right hand side caused the text to break onto another line.  But I don't think that was all of it - seemed more finnicky than just that.

I'm pretty sure I've fixed the bug (bugs?) you are hitting since tagging 0.1.  I've been unable to reproduce it after updating to dvui main - https://github.com/JosephABudd/issue/pull/1

Is updating to main something that you can do?  I could tag a 0.2 soon if that would help?

**Comment by JosephABudd** [comment]
No need to apologize. I'm having too much fun learning dvui and I'm not in a hurry.

I'm familiar with enough with build.zig.zon and build.zig and git submodules for vendoring but I keep getting a build error that I don't get when I use the release url and hash in build.zig.zon.

Yesterday  I tried using `zig fetch https://github.com/david-vanderson/dvui/archive/74c893407cc38e88aad9402bb8a6a1139933ee06.tar.gz --save` but kept getting a build error. I tried it again today and same thing.

Today I also tried `git submodule add https://github.com/david-vanderson/dvui` and I'm getting a build error so I guess I don't understand how to **update to dvui main**.

Obviously I'm not understanding something. I can easily wait for the next release. However, if the instructions for **updating to main** are simple enough you can post them here.

**Comment by david-vanderson** [comment]
Yes - sorry that was confusing.  When I say "update to main" I mean changing the url/hash that's in build.zig.zon (and also updating any code changes that are necessary).

I did that work for your sample in https://github.com/JosephABudd/issue/pull/1 - It does everything needed to update that sample to dvui main.  Does that pull request make sense to you?

**Comment by JosephABudd** [comment]
Nice work. You fixed it.
