### ISSUE TITLE
Zoom above 1 causes horizontal menu not to render.

### ISSUE THREAD

**Issue by JosephABudd** [david-vanderson/dvui#31]
At [OKP](https://github.com/JosephABudd/okp) in [frontend/api.zig](https://github.com/JosephABudd/okp/blob/main/src/okp/frontend/api.zig), lines 32 - 58, fn frame is shown below.

```zig
pub fn frame(arena: std.mem.Allocator) !void {
    // If set the zoom here then
    // 1. there is no app menu. ( a horzontal menu )
    // 👍 the zoom works,

    // The main menu.
    try _main_menu_.frame(all_screens.?);

    // If set the zoom here then
    // 👍 the app menu works and as expected has no zoom,
    // 👍 the vertical tabs work correctly,
    // 👍 the zoom works,
    // 1. my horizontal tabs are not visible, ( a copy of the horizontal menu code )
    // 👍 but the default tab's content is visible as expected.

    // set the zoom.
    const theme: *dvui.Theme = dvui.themeGet();
    const font_body_size: f32 = theme.font_body.size;
    const scale_val: f32 = @round(font_body_size * 2.0) / font_body_size;
    var scaler = try dvui.scale(@src(), scale_val, .{ .expand = .both });
    defer scaler.deinit();

    // Only frame visible screens and panels.
    try all_screens.?.frame(arena);

    // If set the zoom here then obviously no zoom.
}
```

**Comment by david-vanderson** [comment]
Sorry about that.  The underlying problem was that the ScaleWidget stacked all its children on top of each other.  I've committed a fix for this - it now implicitly adds a vertical BoxWidget inside the ScaleWidget so multiple children will show up.

I was able to spot the problem using the debug window.  I clicked "Debug Under Mouse (until click)" and then moused over various stuff and it looked like the tabs were there but were being overdrawn:
![debug_screenshot](https://github.com/david-vanderson/dvui/assets/3290996/ab5851eb-097b-4f70-b216-1bbfe5251625)

I'm trying to make the debug window more useful, so let me know if you have any ideas there.

Finally, if you want to scale the entire UI (including popups/menus/dialogs), then you can adjust Window.content_scale.

Does that all make sense?

**Comment by JosephABudd** [comment]
Thanks. I missed seeing that with the debug window. The debug window has been very helpful.

**Comment by JosephABudd** [comment]
All done.
