### ISSUE TITLE
raster image support

### ISSUE THREAD

**Issue by iacore** [david-vanderson/dvui#32]
I feel like there is the need for this basic widget with fixed size.

**Comment by david-vanderson** [comment]
Yes I really need to make that happen.  Is stb_image the way to go here?

**Comment by iacore** [comment]
I use SDL's `IMG_load`, but it's a bit buggy. You can also replace freetype with stb_truetype

**Comment by david-vanderson** [comment]
I've added stb_image support that follows the same api as the icon stuff.  See the examples basic widget section where it now shows the zig favicon.  Is that working for you?

Because of some zig issues that are still pending, I had to package stb_image as a separate library (just like freetype).  Will revisit using stb_truetype in the future.

Thanks for the push!

**Comment by iacore** [comment]
The image size is weird. The icon is 16x16 (pixel). In the source code the icon size is 12 (what unit?).

dvui:
![image](https://github.com/david-vanderson/dvui/assets/74560659/1d1046bb-746c-4351-a833-3eee1ef00f69)

pixel-perfect:
![image](https://github.com/david-vanderson/dvui/assets/74560659/367e3ee5-686e-4c6e-ad4e-fc8cb7ae1330)

**Comment by iacore** [comment]
What the demo app looks like (standalone-sdl)
![image](https://github.com/david-vanderson/dvui/assets/74560659/7b90a997-a26a-46be-a651-9a542005e990)

**Comment by david-vanderson** [comment]
All the sizes in dvui are in "virtual pixels" which is a kind of arbitrary unit, because it can be altered by the content scale, the natural scale, and the scale widget.  Usually bilinear filtering is what you want, but I should and will change the example to show how to display it at the natural size of the image.

Can you paste the terminal output of `zig build sdl-test` and what size/resolution your monitor is?  Maybe the content scale calculation is going wrong.

**Comment by iacore** [comment]
```
❯ zig-out/bin/sdl-test 
SDL2 dpi 141.76744079589844 guessing backend scale 2
initial window logical Size{ 956 1052 } pixels Size{ 956 1052 } natural scale 1 initial content scale 2 snap_to_pixels false
```

Do not trust SDL2 dpi! It is calculated by taking the physical pixels per inch, which isn't what software uses.

My screen DPI is 96.

I hit this exact problem before: https://github.com/fabioarnold/MiniPixel/pull/45

Don't trust SDL!

**Comment by david-vanderson** [comment]
Ooph this is difficult.  SDL3 will hopefully fix this problem for us, but I'm trying to not sink a ton of effort into it before then.  You can disable it by setting QT_AUTO_SCREEN_SCALE_FACTOR to 0 (see ae758393c3072f86ab9e134e1988df4a68a89abb)

Is SDL2's dpi calculation reasonable for the physical pixel size?  With a width of 956 and dpi of 141, is your screen about 6.8 inches wide?

**Comment by iacore** [comment]
nope it's about 34.5 cm or 13.6 inch wide

**Comment by david-vanderson** [comment]
Oh boy, so the dpi from SDL is just plain wrong for you?

The problem is that people's expectations are changing.  It used to be that people expected a 1-to-1 logical-to-physical pixel thing, so as the pixels got smaller the whole UI got smaller.  But as high dpi screens have become common, the UIs would be unusably small, so now people with "high enough" dpi usually expect the UI to be scaled.

Unfortunately it's been quite a mess in the various different environments (windows had multiple versions of hidpi apis, macos had the @2x stuff, linux depends on wayland/x11 and which desktop environment, etc.).  It looks like the result will be that applications have to handle the scaling themselves, and each environment provides the user a way to indicate the "content scale factor" and a way to query the ratio of logical to physical pixels.  Logical in this case means something like 72 or 96 logical pixels per inch.

SDL3 will hopefully give us this information, but until then I'm afraid we are left with hacks and environment variables.  I added the SDL2 dpi heuristic based on other user's requests.  I'd love to make it better, but I don't know how.  Do you know how to tell when the SDL2 dpi calculation is likely to be wrong?  Or is setting an environment variable the best we can do for now?

**Comment by iacore** [comment]
> Do you know how to tell when the SDL2 dpi calculation is likely to be wrong? 
You... you can't tell. :cry:

> Or is setting an environment variable the best we can do for now?
Use DPI reported by X11. code in  https://github.com/fabioarnold/MiniPixel/pull/45

**Comment by david-vanderson** [comment]
Thanks!  I've added code to call "xrdb -get Xft.dpi" and use that preferentially.  From what I read, it should report the same value without having to link to the X11 lib.

Does that fix it for you?

**Comment by iacore** [comment]
> Does that fix it for you?
Sadly no

`xrdb -get Xft.dpi` returns nothing for me.

Also, it seems like that X11 can have multiple screens, each with its own pixel density.

**Comment by david-vanderson** [comment]
Ok, I removed the SDL_GetDisplayDPI() - can you test again?

As for multiple screens, that is not something I'm going to worry about until SDL3 shows up, which should have proper support for it.

**Comment by iacore** [comment]
Now it works! It is back to the resolution I'm used to.

**Comment by david-vanderson** [comment]
Excellent.  Thanks for sticking with it!

**Comment by iacore** [comment]
Maybe you can add an option to set DPI at runtime? I don't need it, but some people need it

**Comment by david-vanderson** [comment]
Right now the only place that uses dpi is `Window.content_scale`.  SDLBackend sets it initially, but then people can override it if needed.  Either via code or via environment variables (QT_SCALE_FACTOR and GDK_SCALE right now).

The hope is that nobody ever needs to adjust it manually, and with SDL3 we can react to the events notifying that the dpi has changed and adjust content_scale appropriately.  That's the plan but who knows if it'll work out that way.
