### ISSUE TITLE
Scaling issue on KDE Plasma 5 (X11 and Wayland)

### ISSUE THREAD

**Issue by AnErrupTion** [david-vanderson/dvui#43]
I think ever since commit b5d4f2267be1d8222168dab9688422a0c3d32d80, I've been getting weird scaling issues within DVUI on KDE Plasma 5 (Void Linux), X11 and Wayland:

![image](https://github.com/david-vanderson/dvui/assets/49339966/41531f1b-27bc-4c88-b2d1-b2d3558d18a0)

As you can see, everything's just way too big. I tried on Cinnamon (LMDE) and the issue does not occur.

**Comment by david-vanderson** [comment]
Thanks for the report!  I will investigate.  Do you know if I run the Void linux live image, does it have KDE Plasma 5 on it?

**Comment by david-vanderson** [comment]
I should have asked - when you run `zig build sdl-test`, what line does it output that starts with `initial window logical...`?

**Comment by AnErrupTion** [comment]
> Do you know if I run the Void linux live image, does it have KDE Plasma 5 on it?

Nope, it only has XFCE on it unfortunately. Though I don't believe this to be a distribution-specific issue.

> I should have asked - when you run zig build sdl-test, what line does it output that starts with initial window logical...?

``initial window logical Size{ 1600 1048 } pixels Size{ 1600 1048 } natural scale 1 initial content scale 2 snap_to_pixels false``

**Comment by david-vanderson** [comment]
Do you get a line that starts with `SDL2 dpi`?

**Comment by AnErrupTion** [comment]
> Do you get a line that starts with `SDL2 dpi`?

I do, it says: ``SDL2 dpi 144.3789520263672 guessing backend scale 2``

**Comment by david-vanderson** [comment]
Interesting!  Usually with a dpi value that high (if accurate) it indicates a hi dpi situation.  Is that dpi value accurate for your monitor?

**Comment by AnErrupTion** [comment]
> Interesting! Usually with a dpi value that high (if accurate) it indicates a hi dpi situation. Is that dpi value accurate for your monitor?

I actually have no idea 😅... all I know is that it's a 1080p display on my 15.6" laptop, so I'm guessing it is pretty HiDPI.

**Comment by david-vanderson** [comment]
Haha!  No problem.  Guessing that the laptop screen is 16:9 ratio, that gives a horizontal dpi of around `1600.0 / 13.5 = ~118` and vertical `1048 / 7.6 = ~137.9`.  So SDL2 reporting ~144 seems like it's probably correct.

Here's my current thinking about dpi stuff.  We're currently in a tricky spot in the middle of the whole ecosystem moving towards hidpi stuff by default.

Where we want to be is getting the information directly from the backend.  Once SDL3 is released, we should get both the natural scale (difference between the window coords and the render coords) and the content scale (the desktop environment scaling factor) from SDL3.  And SDL3 would take care of getting the content scale from windows/mac/gnome/kde/... however that works.

Where we are right now is trying to do a good enough job for most people while not having a ton of environment-specific calls to get the content scale.

One low-effort thing we could try is inspecting some environment variables.  Since you are using KDE, some quick searching suggests `QT_SCALE_FACTOR` might work here.  Do you have that in your environment (for bash shells, run `export`)?

**Comment by AnErrupTion** [comment]
> Since you are using KDE, some quick searching suggests QT_SCALE_FACTOR might work here. Do you have that in your environment (for bash shells, run export)?

I don't, but I do have this:
```
PLASMA_USE_QT_SCALING 1
QT_AUTO_SCREEN_SCALE_FACTOR 0
QT_WAYLAND_FORCE_DPI 96
```

**Comment by david-vanderson** [comment]
Very interesting.  I assume that somewhere in the KDE settings there is a content scale setting.  Some searching says it's called "global scaling".  When you change that, does it affect any of the environment variables?  (I'm not sure, but you'd at least have to launch a new shell after changing the setting)

**Comment by AnErrupTion** [comment]
> Very interesting. I assume that somewhere in the KDE settings there is a content scale setting. Some searching says it's called "global scaling". When you change that, does it affect any of the environment variables? (I'm not sure, but you'd at least have to launch a new shell after changing the setting)

The only setting I can find is "Scale" in Display Configuration, and it's set to 100%. Changing to 75% does not change the content scale (at least the one guessed by SDL2), but all applications take that new scale so I'm assuming a logout isn't required here.

**Comment by david-vanderson** [comment]
Okay.  Hopefully once SDL3 is live we'll be able to get scale change events, but until then we probably won't automatically change on the fly.

In the meantime, I've pushed a commit to inspect the following on startup:
QT_AUTO_SCREEN_SCALE_FACTOR
QT_SCALE_FACTOR
GDK_SCALE

Does that make things better for you?

**Comment by AnErrupTion** [comment]
> Does that make things better for you?

It definitely does! Now scaling is back to how it was before. :D

**Comment by david-vanderson** [comment]
Excellent.  Thanks!
