### ISSUE TITLE
Document Backend Functions

### ISSUE THREAD

**Issue by VisenDev** [david-vanderson/dvui#83]
Provide documentation on the precise purpose of each Backend function. This will make it easier for contributors to add implement new backends

**Comment by iacore** [comment]
## About rendering API

https://github.com/david-vanderson/dvui/issues/78#issuecomment-2267165939

SDL has a software renderer and OpenGL.

https://github.com/david-vanderson/dvui/issues/77#issuecomment-2256452866
> getting the size of the window and accessing the clipboard

Those are managed by X11/Wayland/whatever similar. Not GL.

https://github.com/david-vanderson/dvui/issues/83

Raylib uses OpenGL.

**Comment by david-vanderson** [comment]
@iacore I think you are correct.  The current design of the backend api is largely just the accumulation of things I needed as they came up, and needs some serious thought.  I've been putting it off because I'm hoping to have a few more backends to understand what API is needed to work for them all.

I'm really hoping there's an option that doesn't have us make our own rendering abstraction.  I was thinking that most uses of dvui would be in an application/game that had already chosen a specific graphics layer.  If that was true, then maybe we do more like imgui - our "rendering" functions would return triangles and it's up to the application to draw them (we would include helper functions in each backend to support this).

If we can pull that off, then it saves us from having to support a whole generic drawing api.  We can say we have this subset, and if you need more complex stuff, you'll need to add a separate library, or directly use the underlying graphics api.

Examples:
- a normal gui application (like podcast player) would only ever use dvui, doesn't need more complex drawing
- a game (dvui only used for debugging windows) likely already has drawing code, no reason to duplicate
- a gui application (like pixel editor) mostly uses dvui, but needs 1 (or a few) places where it wants complete control over how the drawing works

Does that sound reasonable?  Can you think of an example that would want complex drawing code at the dvui layer over doing it at the backend layer?

**Comment by iacore** [comment]
What's more important, those games would have their own control loop already, so dvui doesn't have control over the control loop.

**Comment by iacore** [comment]
> Record the draw calls and replay them. The downside is the memory needed to store draw calls. It's better for dvui to not require remembering draw calls.
> 
>  With that said, there could be a backend that does exactly this.

I have made sdl-standalone work with this approach in the `rr` branch. Please take a look.

**Comment by david-vanderson** [comment]
We documented the existing functions, so I'll close this issue.  I think the other stuff is in other issues, but open new ones if needed.
