### ISSUE TITLE
still rendering when window is unactive/hidden

### ISSUE THREAD

**Issue by lost22git** [david-vanderson/dvui#96]
![Screenshot 2024-08-12 062232](https://github.com/user-attachments/assets/978b16b5-b80e-4851-bece-b7ca68869ce2)

Not sure if it's due to the way immediate mode works

**Comment by VisenDev** [comment]
We probably are not checking if the window is focused/visible during the event loop in the ontop example. We would just need to disable rendering until the window is visible/focused again.

My guess would be that this is caused because the ontop example does not manage the FPS based on events like the standalone version. I don't think the standalone will render new frames if nothing is happening.

**Comment by david-vanderson** [comment]
Oh that is interesting!  Can you provide details about what OS/platform you are on?

**Comment by lost22git** [comment]
OS: Windows 11 (Pro) x86_64
Kernel: WIN32_NT 10.0.22631.3880 (23H2)

**Comment by lost22git** [comment]
Another issue is: cannot show window after window minimized

![2](https://github.com/user-attachments/assets/a1fa9117-f3a6-4e48-8a92-5755f6b75a76)

**Comment by david-vanderson** [comment]
Thanks for the info and screencast!  Give me some time to investigate.

**Comment by david-vanderson** [comment]
I've pushed a commit that hopefully fixes the inability to show the window after minimizing it.  Does that work now?  If so, did it make any difference for the first problem?

**Comment by lost22git** [comment]
It works fine now!
